punishments:
  level1:
    - "eco take %player% 500"
    - "say &4Player &e%player%&4 was fined &e$500&4 for use of the &e 1st level&4 offense."
  level2:
    - "eco take %player% 1000"
    - "say &4Player &e%player%&4 was fined &e$1000&4 for use of the &e 1st level&4 offense."
words:
  level1:
    - debil
    - idiot
    - shit
  level2:
    - cunt
    - fucktard